pipeline:
  build:
    image: docker
    commands:
      - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD registry.sklirg.io
      - docker build -t registry.sklirg.io/wcgstats-scraper:latest .
      - docker push registry.sklirg.io/wcgstats-scraper:latest
    when:
      branch: master
      event: push
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
